In [48]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [49]:
df=pd.read_excel('C:\\Users\\V R N S Nikhil\\OneDrive\\Desktop\\4th_sem\\ML\\FINAL\\ML\\Auto.xlsx')
df.head()

embed_0   embed_1   embed_2   embed_3   embed_4   embed_5   embed_6  \
0  0.021264 -0.062539  0.037466  0.008415  0.021944 -0.033980 -0.032459   
1  0.118235 -0.355940  0.218491  0.049605  0.127147 -0.198309 -0.189919   
2  0.110115 -0.332855  0.198530  0.045706  0.121383 -0.185459 -0.174967   
3  0.107031 -0.318721  0.194099  0.043919  0.113737 -0.178247 -0.171596   
4  0.039461 -0.120917  0.070453  0.015506  0.044520 -0.068256 -0.065418   

    embed_7   embed_8   embed_9  ...  embed_375  embed_376  embed_377  \
0  0.016812 -0.005587  0.040213  ...   0.026886  -0.009761  -0.044234   
1  0.094275 -0.027845  0.232032  ...   0.143506  -0.062857  -0.250240   
2  0.090232 -0.024541  0.219142  ...   0.132716  -0.058603  -0.234703   
3  0.082715 -0.025615  0.205249  ...   0.128095  -0.054040  -0.223192   
4  0.033927 -0.008496  0.075821  ...   0.049817  -0.020045  -0.086780   

   embed_378  embed_379  embed_380  embed_381  embed_382  embed_383  output  
0  -0.036922   0.056197  -0.020517  -0.020927   0.014223   0.028633     0.0  
1  -0.216977   0.323362  -0.105402  -0.113169   0.079825   0.163297     0.0  
2  -0.202833   0.304238  -0.102211  -0.103895   0.076962   0.152439     0.0  
3  -0.193014   0.288106  -0.093294  -0.103034   0.071439   0.148059     0.0  
4  -0.071799   0.111417  -0.039462  -0.041123   0.028038   0.057403     0.0  

[5 rows x 385 columns]

In [50]:
x=df.drop('output',axis=1)
y=df['output']

In [51]:
def custom_round(value):
    integer_part = int(value)
    decimal_part = value - integer_part
    if decimal_part == 0.5:
        return value
    else:
        return round(value)

df['output'] = df['output'].apply(custom_round)
df['output'].value_counts()


output
3.0    272
4.0    262
2.0    186
5.0    131
2.5     64
1.0     62
4.5     52
3.5     44
0.5     22
1.5     19
0.0     13
Name: count, dtype: int64

In [52]:
from sklearn.neighbors import KNeighborsRegressor

In [53]:
base=KNeighborsRegressor()

In [54]:
help(KNeighborsRegressor)

Help on class KNeighborsRegressor in module sklearn.neighbors._regression:

class KNeighborsRegressor(sklearn.neighbors._base.KNeighborsMixin, sklearn.base.RegressorMixin, sklearn.neighbors._base.NeighborsBase)
 |  KNeighborsRegressor(n_neighbors=5, *, weights='uniform', algorithm='auto', leaf_size=30, p=2, metric='minkowski', metric_params=None, n_jobs=None)
 |  
 |  Regression based on k-nearest neighbors.
 |  
 |  The target is predicted by local interpolation of the targets
 |  associated of the nearest neighbors in the training set.
 |  
 |  Read more in the :ref:`User Guide <regression>`.
 |  
 |  .. versionadded:: 0.9
 |  
 |  Parameters
 |  ----------
 |  n_neighbors : int, default=5
 |      Number of neighbors to use by default for :meth:`kneighbors` queries.
 |  
 |  weights : {'uniform', 'distance'}, callable or None, default='uniform'
 |      Weight function used in prediction.  Possible values:
 |  
 |      - 'uniform' : uniform weights.  All points in each neighborhood
 |

In [55]:
from sklearn.preprocessing import StandardScaler

In [56]:
std=StandardScaler()

In [57]:
from sklearn.model_selection import train_test_split

In [58]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [59]:
x_train


embed_0   embed_1   embed_2   embed_3   embed_4   embed_5   embed_6  \
1038  0.119591 -0.364756  0.221722  0.051217  0.130818 -0.204309 -0.192629   
670   0.135907 -0.407778  0.244418  0.055577  0.147634 -0.228675 -0.213624   
65    0.121086 -0.362031  0.213713  0.046726  0.131476 -0.202394 -0.191518   
398   0.086001 -0.247829  0.147858  0.031002  0.090651 -0.136967 -0.130318   
736   0.131503 -0.383240  0.228960  0.052220  0.138992 -0.213234 -0.201818   
...        ...       ...       ...       ...       ...       ...       ...   
121   0.062200 -0.180021  0.107604  0.020736  0.065595 -0.097972 -0.093655   
1044  0.125614 -0.379548  0.226704  0.053020  0.136851 -0.212487 -0.199456   
1095  0.117351 -0.352223  0.213316  0.048285  0.126669 -0.196563 -0.186547   
860   0.116168 -0.341668  0.204554  0.043493  0.124452 -0.190208 -0.179434   
1126  0.156090 -0.476668  0.287441  0.067078  0.173144 -0.266613 -0.250478   

       embed_7   embed_8   embed_9  ...  embed_374  embed_375  embed_376  \
1038  0.098380 -0.027509  0.238845  ...   0.083360   0.146070  -0.065092   
670   0.112362 -0.031690  0.269415  ...   0.094018   0.162805  -0.072522   
65    0.100057 -0.028272  0.236532  ...   0.083509   0.145430  -0.062464   
398   0.069370 -0.020755  0.162137  ...   0.058519   0.101364  -0.041098   
736   0.106372 -0.030078  0.250652  ...   0.087214   0.153530  -0.066565   
...        ...       ...       ...  ...        ...        ...        ...   
121   0.049929 -0.015987  0.116962  ...   0.041748   0.073103  -0.028783   
1044  0.103805 -0.027504  0.250596  ...   0.087436   0.150906  -0.067120   
1095  0.095011 -0.027718  0.230472  ...   0.080632   0.141761  -0.061543   
860   0.093596 -0.028017  0.223892  ...   0.078897   0.138318  -0.057704   
1126  0.129544 -0.035499  0.314684  ...   0.110827   0.190691  -0.085632   

      embed_377  embed_378  embed_379  embed_380  embed_381  embed_382  \
1038  -0.256890  -0.222640   0.333068  -0.110071  -0.113853   0.083470   
670   -0.288310  -0.249068   0.372877  -0.125391  -0.128712   0.095489   
65    -0.253485  -0.217312   0.329044  -0.114485  -0.116615   0.083932   
398   -0.172875  -0.149434   0.225352  -0.078736  -0.081342   0.057842   
736   -0.269544  -0.232050   0.350790  -0.119714  -0.124775   0.088213   
...         ...        ...        ...        ...        ...        ...   
121   -0.125056  -0.106955   0.163270  -0.057276  -0.058396   0.042487   
1044  -0.269142  -0.231721   0.346891  -0.116463  -0.119788   0.088656   
1095  -0.247406  -0.214658   0.320687  -0.106576  -0.111768   0.081411   
860   -0.238852  -0.206517   0.310346  -0.107060  -0.110444   0.079607   
1126  -0.335684  -0.289997   0.436603  -0.146252  -0.148339   0.111126   

      embed_383  
1038   0.167651  
670    0.188797  
65     0.168407  
398    0.114326  
736    0.177273  
...         ...  
121    0.083078  
1044   0.174879  
1095   0.162433  
860    0.157125  
1126   0.217712  

[788 rows x 384 columns]

In [60]:
scale_x_train=std.fit_transform(x_train)
scale_x_test=std.transform(x_test)

In [61]:
scale_x_train

array([[ 0.65043442, -0.72405525,  0.78341175, ..., -0.65159237,
         0.65790926,  0.72107078],
       [ 1.17605857, -1.17823573,  1.18149206, ..., -1.16026012,
         1.20332422,  1.20739885],
       [ 0.69857567, -0.6952894 ,  0.64294486, ..., -0.74614451,
         0.6788645 ,  0.73845632],
       ...,
       [ 0.57824977, -0.59174795,  0.63598055, ..., -0.58025215,
         0.56444316,  0.6010605 ],
       [ 0.54015023, -0.48031746,  0.48230011, ..., -0.53491987,
         0.48257012,  0.4790046 ],
       [ 1.82626405, -1.90549057,  1.93607307, ..., -1.83208313,
         1.91296334,  1.8724056 ]])

In [62]:
param_grid={'n_neighbors':list(np.arange(100)),
            'weights':['uniform','distance'],
             'metric':['minkowski','euclidean','chebyshev']}

In [63]:
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV
gtkk=GridSearchCV(base,param_grid)

In [64]:
gtkk.fit(scale_x_train,y_train)

c:\Users\V R N S Nikhil\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning: 
30 fits failed out of a total of 3000.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
30 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\V R N S Nikhil\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\V R N S Nikhil\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py", line 1145, in wrapper
    estimator._validate_params()
  File "c:\Users\V R N S Nikhil\AppData\Local\Programs\Python\Pytho

GridSearchCV(estimator=KNeighborsRegressor(),
             param_grid={'metric': ['minkowski', 'euclidean', 'chebyshev'],
                         'n_neighbors': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
                                         12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
                                         22, 23, 24, 25, 26, 27, 28, 29, ...],
                         'weights': ['uniform', 'distance']})

In [65]:
gtkk.best_score_

0.1408111634157064

In [66]:
test = gtkk.predict(scale_x_test)

In [67]:
test

array([2.96238013, 3.62532663, 3.93300315, 2.        , 4.12217726,
       2.73835467, 4.05752386, 2.89581687, 3.11816955, 3.38868405,
       3.61032899, 3.20530494, 3.83737038, 2.99656369, 3.23709502,
       2.83610851, 2.67891599, 3.14472039, 2.5273505 , 2.85130905,
       2.69933283, 3.16155439, 4.08639414, 3.        , 2.94806805,
       2.79773504, 3.08322623, 3.05499017, 2.51353177, 2.76774316,
       2.625     , 4.11762292, 2.91932168, 4.25      , 3.16981583,
       3.35423686, 3.54354839, 3.99096762, 3.3624948 , 2.62603322,
       3.36552941, 3.42246368, 4.5       , 3.93407905, 3.20765936,
       4.02671262, 4.11694342, 3.72187649, 2.29328953, 2.153125  ,
       3.54675273, 3.26383496, 3.28141694, 2.80625792, 3.44706564,
       3.66660903, 3.43886299, 3.42366582, 3.89254743, 2.92542076,
       2.76843522, 2.76458351, 3.04176888, 2.625     , 3.54382291,
       3.40374648, 3.54934125, 2.3125    , 2.52941614, 2.796875  ,
       2.6875    , 2.155646  , 3.28959761, 3.27963592, 3.01937

In [68]:
from sklearn.metrics import mean_squared_error,r2_score

In [69]:
np.sqrt(mean_squared_error(y_test,test))

1.051013516357428

In [70]:
ddd=RandomizedSearchCV(base,param_grid)
ddd

RandomizedSearchCV(estimator=KNeighborsRegressor(),
                   param_distributions={'metric': ['minkowski', 'euclidean',
                                                   'chebyshev'],
                                        'n_neighbors': [0, 1, 2, 3, 4, 5, 6, 7,
                                                        8, 9, 10, 11, 12, 13,
                                                        14, 15, 16, 17, 18, 19,
                                                        20, 21, 22, 23, 24, 25,
                                                        26, 27, 28, 29, ...],
                                        'weights': ['uniform', 'distance']})

In [71]:
ddd.fit(scale_x_train,y_train)

RandomizedSearchCV(estimator=KNeighborsRegressor(),
                   param_distributions={'metric': ['minkowski', 'euclidean',
                                                   'chebyshev'],
                                        'n_neighbors': [0, 1, 2, 3, 4, 5, 6, 7,
                                                        8, 9, 10, 11, 12, 13,
                                                        14, 15, 16, 17, 18, 19,
                                                        20, 21, 22, 23, 24, 25,
                                                        26, 27, 28, 29, ...],
                                        'weights': ['uniform', 'distance']})

In [72]:
test1=ddd.predict(scale_x_test)

In [73]:
test1


array([3.09194505, 3.42033197, 3.50649365, 2.        , 3.62604975,
       3.08163066, 3.4736917 , 3.17990545, 3.23507564, 3.42915504,
       3.49976952, 3.26039209, 3.41432371, 3.15424893, 3.37366701,
       2.80507572, 2.95146247, 3.42117235, 2.70036489, 2.93496101,
       2.76457668, 3.20907403, 3.40129876, 3.        , 3.09868915,
       2.82116071, 3.25151988, 2.94419672, 2.99390409, 3.11860008,
       2.625     , 3.55048663, 3.0604558 , 4.25      , 3.20533921,
       3.30979815, 3.33488551, 3.35614926, 3.32003916, 3.02543584,
       3.50475158, 3.32530541, 4.5       , 3.5597543 , 3.35003545,
       3.62220065, 3.49168998, 3.40448282, 3.18930643, 2.153125  ,
       3.53790776, 3.39530549, 3.29056837, 2.99231795, 3.43471461,
       3.46540812, 3.45457363, 3.48659276, 3.47592023, 3.18277435,
       3.16691161, 2.95313752, 2.89007766, 2.625     , 3.42028748,
       3.24104954, 3.48491871, 2.3125    , 2.90712952, 2.796875  ,
       2.6875    , 2.75285858, 3.39454793, 3.32042643, 3.37761

In [74]:
mean_squared_error(y_test,test)

1.1046294115660051

In [75]:
r2_score(y_test,test)

0.17850944374818045

In [76]:
from sklearn.decomposition import KernelPCA,IncrementalPCA

In [77]:
knnn=KernelPCA(n_components=100)
scale_x_train_pca=knnn.fit_transform(scale_x_train)
scale_x_test_pca=knnn.transform(scale_x_test)

In [78]:
x=KNeighborsRegressor()
x.fit(scale_x_train_pca,y_train)


KNeighborsRegressor()

In [79]:
param_grid={'n_neighbors':list(np.arange(100)),
            'weights':['uniform','distance'],
             'metric':['minkowski','euclidean','chebyshev']}

In [80]:
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV
gtkk=GridSearchCV(x,param_grid)


In [81]:
gtkk.fit(scale_x_train_pca,y_train)


c:\Users\V R N S Nikhil\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning: 
30 fits failed out of a total of 3000.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
30 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\V R N S Nikhil\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\V R N S Nikhil\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py", line 1145, in wrapper
    estimator._validate_params()
  File "c:\Users\V R N S Nikhil\AppData\Local\Programs\Python\Pytho

GridSearchCV(estimator=KNeighborsRegressor(),
             param_grid={'metric': ['minkowski', 'euclidean', 'chebyshev'],
                         'n_neighbors': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
                                         12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
                                         22, 23, 24, 25, 26, 27, 28, 29, ...],
                         'weights': ['uniform', 'distance']})

In [82]:
testtt=gtkk.predict(scale_x_test_pca)

In [83]:
testtt


array([3.00861005, 3.34739812, 3.42821478, 2.00000933, 3.32328843,
       2.95779941, 3.31068518, 3.2081757 , 3.04994362, 3.06688011,
       3.12397479, 3.11812424, 3.27828968, 3.19199576, 3.17175773,
       2.92962915, 3.09479959, 3.23822381, 3.04690312, 3.21919973,
       2.92520842, 3.07384091, 3.23371952, 3.        , 3.2139558 ,
       2.86978959, 3.22615637, 2.97457924, 3.05659772, 3.17546262,
       2.62500546, 3.39624669, 3.2212032 , 4.2499937 , 3.22732257,
       3.15173193, 3.18900142, 3.17371068, 3.32689426, 3.02457251,
       3.35171618, 3.11509226, 4.5       , 3.2796556 , 3.25279985,
       3.48071722, 3.35261365, 3.12515876, 3.23376149, 2.65625   ,
       3.35690105, 3.34124377, 3.13333872, 2.95145543, 3.30389214,
       3.27118612, 3.32265053, 3.32140964, 3.34340011, 3.20101267,
       3.1125189 , 2.98608829, 3.08926786, 2.625     , 3.21843977,
       3.2960344 , 3.53110904, 2.3125    , 2.99739214, 2.375     ,
       2.6875    , 3.06164441, 3.16382805, 3.28438608, 3.12062

In [84]:
r2_score(y_test,testtt)

0.027852801055889054

In [85]:
incr=IncrementalPCA(n_components=200)
scale_x_train_pca1=incr.fit_transform(scale_x_train)
scale_x_test_pca1=incr.transform(scale_x_test)

In [86]:
scale_x_test_pca1

array([[ 8.57156682e+00,  1.65373849e+00,  2.00771147e+00, ...,
         4.22757741e-03, -2.57677271e-04,  8.72064899e-03],
       [-2.56625777e+01,  2.48656815e+00, -2.59051987e+00, ...,
        -5.07820821e-03,  2.13727012e-04, -1.65382227e-03],
       [-1.35247645e+01,  2.34705410e+00,  1.23076651e+00, ...,
         2.58448453e-03, -2.07890875e-03,  4.07132340e-03],
       ...,
       [-2.41080685e+01,  2.75840708e+00, -7.81424536e-01, ...,
         5.28952818e-03,  3.62975411e-03, -6.46441602e-03],
       [-1.76455906e+01,  7.04816945e-01, -1.57901927e-01, ...,
         9.13331420e-05, -1.96168968e-03,  4.01798274e-03],
       [-1.67000079e+01, -1.67559018e+00, -4.38307946e-01, ...,
         2.89758067e-03, -5.01381280e-03, -1.69350702e-03]])

In [87]:
np.sum(incr.explained_variance_ratio_)

0.9999956286434346

In [88]:
param_grid={'n_neighbors':list(np.arange(100)),
            'weights':['uniform','distance'],
             'metric':['minkowski','euclidean','chebyshev']}

In [89]:
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV
gtkk1=GridSearchCV(x,param_grid)


In [90]:
gtkk1.fit(scale_x_train_pca1,y_train)

c:\Users\V R N S Nikhil\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning: 
30 fits failed out of a total of 3000.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
30 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\V R N S Nikhil\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\V R N S Nikhil\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py", line 1145, in wrapper
    estimator._validate_params()
  File "c:\Users\V R N S Nikhil\AppData\Local\Programs\Python\Pytho

GridSearchCV(estimator=KNeighborsRegressor(),
             param_grid={'metric': ['minkowski', 'euclidean', 'chebyshev'],
                         'n_neighbors': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
                                         12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
                                         22, 23, 24, 25, 26, 27, 28, 29, ...],
                         'weights': ['uniform', 'distance']})

In [91]:
test1111=gtkk1.predict(scale_x_test_pca1)

In [92]:
test1111

array([3.00863522, 3.34739594, 3.42808681, 2.00001317, 3.32329553,
       2.9580543 , 3.31041621, 3.20821399, 3.04995326, 3.06700939,
       3.12421695, 3.1175753 , 3.2873993 , 3.19208693, 3.16347041,
       2.92963193, 3.09481143, 3.23803593, 3.0471481 , 3.219354  ,
       2.92522736, 3.07386652, 3.23350816, 3.        , 3.2139957 ,
       2.86937891, 3.22615083, 2.97833499, 3.05669281, 3.17555924,
       2.62500437, 3.39617652, 3.22144551, 4.24999486, 3.22714352,
       3.15176167, 3.18892967, 3.17368119, 3.32682685, 3.02461258,
       3.35178609, 3.11488452, 4.49999228, 3.279567  , 3.25272852,
       3.48021757, 3.35257759, 3.1252139 , 3.23428158, 2.15312721,
       3.35688923, 3.34118202, 3.13337357, 2.95156772, 3.30386479,
       3.27107434, 3.32264284, 3.32134863, 3.3433775 , 3.20079307,
       3.11256343, 2.98583362, 3.08954595, 2.625     , 3.21846148,
       3.29592231, 3.53108343, 2.31250679, 2.99761148, 2.79687525,
       2.68750037, 3.06170079, 3.1637923 , 3.28422188, 3.12065

In [93]:
np.sqrt(mean_squared_error(y_test,test1111))

1.1442316094808875

In [94]:
r2_score(y_test,test1111)

0.02632536871155211